# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Caryn Geady, Kaitlyn Kobayashi
author_email: bhklab.katyscott@gmail.com
author_full_name: Katy Scott
github_username: strixy16
has_additional_authors: true
project_description: 'Simulation code accompanying the Retiring the Ruler: Toward
    a Volumetric, Multi-Lesion, Longitudinal Lens on Tumor Response paper.'
project_name: Retiring the Ruler
project_slug: retiring-the-ruler
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
